### ISSUE TITLE
Mekanism Crystalizer crashing with Tinker's ores

### ISSUE THREAD

**Issue by ShadowDrakken** [buttilda/Another-One-Bites-the-Dust#10]
For whatever reason when I put an Tinker's Ardite Ore into Mekanism's 5x processing, it doesn't produce a full 5 ingots, it gets stuck after the 4th one. Trying to open the UI on the Crystalizer to find out what the difference is causes a GUI crash

---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 8/30/14 9:02 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
    at mekanism.client.gui.GuiChemicalCrystallizer.func_146979_b(GuiChemicalCrystallizer.java:97)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:119)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at mekanism.client.gui.GuiChemicalCrystallizer.func_146979_b(GuiChemicalCrystallizer.java:97)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:119)

-- Screen render details --
Details:
    Screen name: mekanism.client.gui.GuiChemicalCrystallizer
    Mouse location: Scaled: (213, 119). Absolute: (427, 240)
    Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

**Comment by buttilda** [comment]
Hm I derped with the registry. Forgot to register the clean slurry.
