### ISSUE TITLE
Steel is broken for Thermal Expansion [1.7.10]4.0.0B6-16

### ISSUE THREAD

**Issue by Junrall** [buttilda/Another-One-Bites-the-Dust#22]
If Thermal Expansion config is set to true, the game crashes upon startup. Setting Thermal Expansion config to false removes the crash.

Here is the error I get:

java.lang.NullPointerException: Ore dictionary item not found: ingotSteel
    at ganymedes01.aobd.recipes.RecipesModule.getOreStack(RecipesModule.java:103)
    at ganymedes01.aobd.recipes.RecipesModule.getOreStack(RecipesModule.java:78)
    at ganymedes01.aobd.recipes.RecipesModule.getOreStack(RecipesModule.java:55)
    at ganymedes01.aobd.recipes.modules.ThermalExpansionModule.initOre(ThermalExpansionModule.java:20)
    at ganymedes01.aobd.recipes.RecipesModule.init(RecipesModule.java:37)
    at ganymedes01.aobd.recipes.ModulesHandler.init(ModulesHandler.java:31)
    at ganymedes01.aobd.AOBD.init(AOBD.java:72)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:691)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
    at org.multimc.EntryPoint.listen(EntryPoint.java:165)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)

**Comment by buttilda** [comment]
Could you give me a list of the mods you have installed?

**Comment by Junrall** [comment]
Ah man!... Before reporting an issue, I should have removed all the mods then added them back in one at a time. Sorry, I know better!

Anyways, here are the mods that, together, are causing the above error:
AOBD-2.3.2
CoFHCore-[1.7.10]3.0.0B8-36
NetherOres-[1.7.10]2.3.0RC3-84
ThermalExpansion-[1.7.10]4.0.0B6-16
ThermalFoundation-[1.7.10]1.0.0B3-8
EnderIO-1.7.10-2.2.1.276

If I remove ONE of the following, the error does not return:
NetherOres
ThermalExpansion
EnderIO

**Comment by buttilda** [comment]
So removing EnderIO causes no crashes whatsoever? That's bizarre... because the crash log says it failed to find any type of Steel Ingot when trying to register a recipe for the Thermal Expansion's pulveriser... I don't see how EIO could have anything to do with that...

**Comment by buttilda** [comment]
But thanks for the extra information, I'll keep testing, so far I haven't managed to reproduce it...

**Comment by Junrall** [comment]
Gah! Once again... I left out information.

I am running the latest Cauldron with Forge 1236: http://cauldron.minecraftforge.net/forums/downloads.37/

**Comment by Junrall** [comment]
What I meant was that my Cauldron server is crashing on startup with the same error. Both client and server are running Forge 1236.
Sorry for the confusion... my mind is in vacation mode!

**Comment by Junrall** [comment]
If it helps...
Steel only shows up in the AOBD config when all three mods are running.
Using NEI and searching for "steel", EnderIO is the one that has couple of steel ingot types (Electrical and Dark steel)... neither of which shows up when you search for "ingot" 

Ok... I'm done now :)

**Comment by buttilda** [comment]
Ohhh that was some good info.
I managed to reproduce it now :D

Thank you a lot :) Will work on a fix, should be quite trivial
